### ISSUE TITLE
Defining modules of type other than `csi` panics with `panic: runtime error: invalid memory address or nil pointer dereference`

### ISSUE THREAD

**Issue by svyotov** [rexray/rexray#1254]
# Summary
Defining modules of type other than CSI will panic
```
modules:
    gp2-100gib:
      type: docker
```
# Bug Reports
## Version
```
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.11.3
OsArch: Linux-x86_64
Commit: 3afc7942dd8b1a88ed902344b4ece89374be87f7
Formed: Tue, 12 Jun 2018 15:45:51 UTC
```

## Expected Behavior
Not to panic, or at least to say unsupported module and to exit.

## Actual Behavior
```
DEBU[0002] found cached instance ID                      host=unix:///var/run/rexray/575787139.sock integrationDriver=linux osDriver=linux server=daisy-hound-sc service=ebs storageDriver=libstorage time=1534351173145 txCR=1534351173 txID=46f82548-c8eb-442b-428f-14f07c4312cd
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x194386b]

goroutine 220 [running]:
github.com/rexray/rexray/agent/csi/libstorage.(*driver).Serve(0xc420283000, 0x336b200, 0xc420052180, 0x7f7006cfdae0, 0xc4200c9080, 0x0, 0x336b200)
	/go/src/github.com/rexray/rexray/agent/csi/libstorage/csi_service_libstorage.go:107 +0x4cb
github.com/rexray/rexray/agent/csi.(*csiService).Serve(0xc420285090, 0x336b200, 0xc420052180, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/rexray/rexray/agent/csi/mod_csi_service.go:72 +0x65
github.com/rexray/rexray/agent/csi.(*mod).Start.func2.1(0xc42041be00, 0x33744a0, 0xc420052180)
	/go/src/github.com/rexray/rexray/agent/csi/mod_csi.go:247 +0x8a
created by github.com/rexray/rexray/agent/csi.(*mod).Start.func2
	/go/src/github.com/rexray/rexray/agent/csi/mod_csi.go:246 +0x57
```

## Steps To Reproduce
  * Add any module definition of type not `csi`
```rexray:
  modules:
    gp2-100gib:
      type: docker
```
## Configuration Files
```yaml
```
rexray:
  logLevel: debug
  modules:
    default-csi:
      desc: "The default CSI module."
      disabled: true
    gp2-100gib:
      logging:
        level: info
      service: ebs
      type: docker
      disabled: false
      desc: 100GiB General Purpose
      # host: /run/docker/plugins/rexray.sock
      host: unix:///run/docker/plugins/gp2-100gib.sock
      spec: /etc/docker/plugins/gp2-100gib.spec
      libstorage:
        service: ebs
        integration:
          volume:
            operations:
              create:
                default:
                  type: gp2
                  size: 100
                  fstype: xfs
libstorage:
  logging:
    level: debug
  service: ebs
  server:
    tasks:
      exeTimeout: 120s
    services:
      ebs:
        driver: ebs
  integration:
    volume:
      operations:
        create:
          default:
            size: 5
        mount:
          preempt: true
ebs:
  accessKey: AWSACCESSKEY
  secretKey: AWSSECRETKEY
  region: AWSREGION
```
## Opinion
Attempting to retrieve the configuration `szTimeout := d.config.GetString("csi.libstorage.timeout")` will panic as the code ```// Check for a gofig.Config in the context.
	if config, ok := d.ctx.Value(ctxConfigKey).(gofig.Config); ok {
		d.ctx.Warn(fmt.Sprintf("init csi libstorage bridge w ctx.config for key: %q", ctxConfigKey))
		d.config = config
		d.mntPath = d.config.GetString(apitypes.ConfigIgVolOpsMountPath)
	}``` will never be ok, as the key `ctxConfigKey` defined as `ctxConfigKey     = interface{}("csi.config")` is not there. 

The code should not panic and if it does not support other module types, should either not have this field or provide the user with an appropriate error.

**Comment by clintkitson** [comment]
Hello @svyotov,

What are you trying to achieve with your configuration?

**Comment by svyotov** [comment]
Hi @clintkitson we were trying to configure volume sizes and other options. CSI will work fine as far as I can see, the issue though was that when providing a different type: docker, which was what version 0.9.0 would work with, it panics. It would be better if it would handle such issues more gracefully and provide with information on what configurations are not valid.
